### ISSUE TITLE
Can't build REPL as described in README

### ISSUE THREAD

**Issue by baryluk** [pillager86/dmildew#4]
Hi.

This works:

```
user@debian:~/dmildew$ dub build --compiler=ldc2
Performing "debug" build using ldc2 for x86_64.
dmildew 0.5.1+commit.2.gaed6a9a: building configuration "library"...
...
user@debian:~/dmildew$
````

This doesn't:

```
user@debian:~/dmildew$ dub build mildew:run 
Package 'mildew:run' was neither found locally nor online.
user@debian:~/dmildew$ dub build --compiler=ldc2 Mildew:run 
Package 'Mildew:run' was neither found locally nor online.
user@debian:~/dmildew$ 
```

DUB version 1.22.0-1, built on Aug  8 2020

**Comment by FateMeetsLuck** [comment]
I probably need to fix the README file. The command on debian should be `dub build :run` and `dub build`. It's only on Windows that you have to write instead `dub build dmildew:run`

**Comment by FateMeetsLuck** [comment]
OK i fixed the README https://github.com/pillager86/dmildew/blob/main/README.md sorry about that. Sometimes I don't pay attention to find and replace in text editors.

**Comment by baryluk** [comment]
Thanks. That works. Also `dub run dmildew:run` runs too.
